<?php
function db(): PDO { static $pdo; if(!$pdo){$pdo=new PDO('sqlite:'.DB_PATH); $pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION); $pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC); $pdo->exec('PRAGMA foreign_keys=ON');} return $pdo; }
function init_db(): void { $p=db();
$p->exec("CREATE TABLE IF NOT EXISTS locations(id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, area TEXT, parent_id INTEGER NULL REFERENCES locations(id), notes TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS containers(id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, type TEXT, location_id INTEGER NOT NULL REFERENCES locations(id), notes TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS items(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, quantity REAL NOT NULL DEFAULT 1, unit TEXT NOT NULL DEFAULT 'Stk', category TEXT, location_id INTEGER NOT NULL REFERENCES locations(id), container_id INTEGER NULL REFERENCES containers(id), location_detail TEXT, notes TEXT, created_at TEXT, updated_at TEXT);
CREATE TABLE IF NOT EXISTS tags(id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS item_tags(item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE, tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE, PRIMARY KEY(item_id,tag_id));
CREATE TABLE IF NOT EXISTS audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT, entity_type TEXT NOT NULL, entity_id INTEGER, action TEXT NOT NULL, old_json TEXT, new_json TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS app_meta(key TEXT PRIMARY KEY, value TEXT);");
seed_initial_data($p); }
function seed_initial_data(PDO $p): void { if((int)$p->query('SELECT COUNT(*) FROM locations')->fetchColumn()>0) return; $t=now(); $ins=$p->prepare('INSERT INTO locations(code,name,area,parent_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)'); $ids=[]; $add=function($c,$n,$a='Büro',$parent=null,$notes='') use($ins,&$ids,$t){$ins->execute([$c,$n,$a,$parent?$ids[$parent]:null,$notes,$t,$t]); $ids[$c]=(int)db()->lastInsertId();}; $add('A01','Schreibtisch / Arbeitsbereich'); $add('S01','Großer Schrank'); for($i=1;$i<=3;$i++)$add("S01-F$i","Fach $i",'Büro','S01'); for($i=1;$i<=6;$i++)$add("S01-D$i","Schublade $i",'Büro','S01','gezählt von oben nach unten'); $add('S02','Sideboard / kleiner Schrank unter Druckern','Büro',null,'aktuell voll, nicht als schnelle Ablage verwenden'); $add('S03','Waschmaschinenschrank / Filament-Hauptlager'); $add('S03-L','Linker Bereich','Büro','S03'); $add('S04','Filament-Überlaufregal'); $add('R01','Bücherregal-Zusatzfach'); $p->prepare('INSERT INTO containers(code,name,type,location_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)')->execute(['B01','Projekt-/Elektronikbox','Box',$ids['A01'],'Schwarze Box auf dem Schreibtischbereich',$t,$t]); }
