<?php
function parse_invpatch(string $json): array { $d=json_decode($json,true); if(json_last_error()) throw new InvalidArgumentException('JSON-Fehler: '.json_last_error_msg()); if(($d['schema']??'')!=='kappa-invpatch/v1') throw new InvalidArgumentException('Schema muss kappa-invpatch/v1 sein.'); if(!isset($d['operations'])||!is_array($d['operations'])) throw new InvalidArgumentException('operations muss ein Array sein.'); return $d; }
function apply_invpatch(string $json, bool $dry=true): array { $d=parse_invpatch($json); $p=db(); $counts=['locations'=>0,'containers'=>0,'items_new'=>0,'items_updated'=>0,'deleted'=>0,'errors'=>[]]; $p->beginTransaction(); try{ foreach($d['operations'] as $idx=>$op){ try{ $name=$op['op']??''; if($name==='upsert_location'){ foreach(['code','name'] as $r) if(empty($op[$r])) throw new InvalidArgumentException("$r fehlt"); $parent=location_id_by_code($op['parent_code']??null); if(!empty($op['parent_code'])&&!$parent) throw new InvalidArgumentException('parent_code existiert nicht: '.$op['parent_code']); $old=location_id_by_code($op['code']); if($old){$p->prepare('UPDATE locations SET name=?,area=?,parent_id=?,notes=?,updated_at=? WHERE code=?')->execute([$op['name'],$op['area']??null,$parent,$op['notes']??null,now(),$op['code']]);} else {$p->prepare('INSERT INTO locations(code,name,area,parent_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)')->execute([$op['code'],$op['name'],$op['area']??null,$parent,$op['notes']??null,now(),now()]); $old=(int)$p->lastInsertId();} audit_log('location',$old,'import_upsert',null,$op); $counts['locations']++; }
elseif($name==='upsert_container'){ foreach(['code','name','location_code'] as $r) if(empty($op[$r])) throw new InvalidArgumentException("$r fehlt"); $loc=location_id_by_code($op['location_code']); if(!$loc) throw new InvalidArgumentException('location_code existiert nicht: '.$op['location_code']); $cid=container_id_by_code($op['code']); if($cid){$p->prepare('UPDATE containers SET name=?,type=?,location_id=?,notes=?,updated_at=? WHERE code=?')->execute([$op['name'],$op['type']??null,$loc,$op['notes']??null,now(),$op['code']]);} else {$p->prepare('INSERT INTO containers(code,name,type,location_id,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?)')->execute([$op['code'],$op['name'],$op['type']??null,$loc,$op['notes']??null,now(),now()]); $cid=(int)$p->lastInsertId();} audit_log('container',$cid,'import_upsert',null,$op); $counts['containers']++; }
elseif($name==='add_item'){ $id=import_item_values($op); $counts['items_new']++; }
elseif($name==='upsert_item'){ $m=$op['match']??[]; if(empty($m['name'])||empty($m['location_code'])) throw new InvalidArgumentException('match.name und match.location_code fehlen'); $loc=location_id_by_code($m['location_code']); $con=container_id_by_code($m['container_code']??null); $sql='SELECT id FROM items WHERE name=? AND location_id=? AND '.(($m['container_code']??null)?'container_id=?':'container_id IS NULL'); $st=$p->prepare($sql); $st->execute(($m['container_code']??null)?[$m['name'],$loc,$con]:[$m['name'],$loc]); $ids=$st->fetchAll(PDO::FETCH_COLUMN); if(count($ids)>1) throw new InvalidArgumentException('Mehrere passende Artikel für upsert_item.'); $vals=$op['values']??[]; $vals['name']=$m['name']; $vals['location_code']=$m['location_code']; $vals['container_code']=$m['container_code']??null; if(count($ids)===1){ import_item_values($vals,(int)$ids[0]); $counts['items_updated']++; } else { import_item_values($vals); $counts['items_new']++; } }
elseif($name==='update_item'){ if(empty($op['id'])) throw new InvalidArgumentException('id fehlt'); if(!get_item((int)$op['id'])) throw new InvalidArgumentException('Artikel-ID existiert nicht'); import_item_values($op['values']??[],(int)$op['id']); $counts['items_updated']++; }
elseif($name==='move_item'){ if(empty($op['id'])||!get_item((int)$op['id'])) throw new InvalidArgumentException('Artikel-ID fehlt/existiert nicht'); $it=get_item((int)$op['id']); $it['location_code']=$op['location_code']??null; $it['container_code']=$op['container_code']??null; $it['location_detail']=$op['location_detail']??null; import_item_values($it,(int)$op['id']); $counts['items_updated']++; }
elseif($name==='delete_item'){ if(empty($op['id'])) throw new InvalidArgumentException('id fehlt'); delete_item((int)$op['id']); $counts['deleted']++; }
else throw new InvalidArgumentException('Unbekannte Operation: '.$name); } catch(Throwable $e){ $counts['errors'][]='Operation '.$idx.': '.$e->getMessage(); throw $e; } } if($dry)$p->rollBack(); else $p->commit(); } catch(Throwable $e){ if($p->inTransaction())$p->rollBack(); if(!$counts['errors'])$counts['errors'][]=$e->getMessage(); } return $counts; }
function import_item_values(array $v, ?int $id=null): int { if(empty($v['name'])) throw new InvalidArgumentException('Artikelname fehlt'); $loc=location_id_by_code($v['location_code']??null); if(!$loc) throw new InvalidArgumentException('location_code fehlt/existiert nicht'); $con=container_id_by_code($v['container_code']??null); if(!empty($v['container_code'])&&!$con) throw new InvalidArgumentException('container_code existiert nicht'); return save_item(['name'=>$v['name'],'quantity'=>$v['quantity']??1,'unit'=>$v['unit']??'Stk','category'=>$v['category']??'','location_id'=>$loc,'container_id'=>$con,'location_detail'=>$v['location_detail']??'','notes'=>$v['notes']??'','tags'=>implode(', ', $v['tags']??[])],$id); }
