<?php
function all_locations(): array { return db()->query('SELECT l.*, p.code parent_code FROM locations l LEFT JOIN locations p ON p.id=l.parent_id ORDER BY COALESCE(p.code,l.code), l.code')->fetchAll(); }
function all_containers(): array { return db()->query('SELECT c.*, l.code location_code, l.name location_name, (SELECT COUNT(*) FROM items i WHERE i.container_id=c.id) item_count FROM containers c JOIN locations l ON l.id=c.location_id ORDER BY c.code')->fetchAll(); }
function location_id_by_code(?string $code): ?int { if(!$code)return null; $s=db()->prepare('SELECT id FROM locations WHERE code=?'); $s->execute([$code]); $v=$s->fetchColumn(); return $v? (int)$v:null; }
function container_id_by_code(?string $code): ?int { if(!$code)return null; $s=db()->prepare('SELECT id FROM containers WHERE code=?'); $s->execute([$code]); $v=$s->fetchColumn(); return $v? (int)$v:null; }
function item_tags(int $id): array { $s=db()->prepare('SELECT t.* FROM tags t JOIN item_tags it ON it.tag_id=t.id WHERE it.item_id=? ORDER BY t.name'); $s->execute([$id]); return $s->fetchAll(); }
function set_item_tags(int $id, array $tags): void { $p=db(); $p->prepare('DELETE FROM item_tags WHERE item_id=?')->execute([$id]); foreach($tags as $name){ $p->prepare('INSERT OR IGNORE INTO tags(name) VALUES(?)')->execute([$name]); $tid=(int)$p->prepare('SELECT id FROM tags WHERE name=?')->execute([$name]); $st=$p->prepare('SELECT id FROM tags WHERE name=?'); $st->execute([$name]); $tagId=(int)$st->fetchColumn(); $p->prepare('INSERT OR IGNORE INTO item_tags(item_id,tag_id) VALUES(?,?)')->execute([$id,$tagId]); }}
function list_items(array $f=[]): array { $where=[];$a=[]; if(($f['q']??'')!==''){ $where[]='(i.name LIKE ? OR i.category LIKE ? OR i.notes LIKE ? OR i.location_detail LIKE ? OR l.code LIKE ? OR l.name LIKE ? OR c.code LIKE ? OR c.name LIKE ? OR EXISTS(SELECT 1 FROM item_tags it JOIN tags t ON t.id=it.tag_id WHERE it.item_id=i.id AND t.name LIKE ?))'; for($x=0;$x<9;$x++)$a[]='%'.$f['q'].'%'; } foreach(['location_id'=>'i.location_id','container_id'=>'i.container_id'] as $k=>$col) if(!empty($f[$k])){$where[]="$col=?";$a[]=$f[$k];} if(($f['category']??'')!==''){$where[]='i.category=?';$a[]=$f['category'];} if(($f['tag']??'')!==''){$where[]='EXISTS(SELECT 1 FROM item_tags it JOIN tags t ON t.id=it.tag_id WHERE it.item_id=i.id AND t.name=?)';$a[]=$f['tag'];} $sort=['name'=>'i.name','category'=>'i.category','location'=>'l.code','updated'=>'i.updated_at DESC']; $sql='SELECT i.*, l.code location_code, l.name location_name, c.code container_code, c.name container_name FROM items i JOIN locations l ON l.id=i.location_id LEFT JOIN containers c ON c.id=i.container_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY '.($sort[$f['sort']??'name']??'i.name'); $s=db()->prepare($sql); $s->execute($a); $rows=$s->fetchAll(); foreach($rows as &$r)$r['tags']=item_tags((int)$r['id']); return $rows; }
function save_item(array $v, ?int $id=null): int { $p=db(); $old=$id?get_item($id):null; $data=[$v['name'],(float)$v['quantity'],$v['unit']?:'Stk',$v['category']?:null,(int)$v['location_id'],($v['container_id']?:null),$v['location_detail']?:null,$v['notes']?:null,now()]; if($id){$data[]=$id; $p->prepare('UPDATE items SET name=?,quantity=?,unit=?,category=?,location_id=?,container_id=?,location_detail=?,notes=?,updated_at=? WHERE id=?')->execute($data);} else {$data[]=now(); $p->prepare('INSERT INTO items(name,quantity,unit,category,location_id,container_id,location_detail,notes,updated_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)')->execute($data); $id=(int)$p->lastInsertId();} set_item_tags($id,csv_tags($v['tags']??'')); audit_log('item',$id,$old?'update':'create',$old,get_item($id)); return $id; }
function get_item(int $id): ?array { $s=db()->prepare('SELECT * FROM items WHERE id=?'); $s->execute([$id]); $r=$s->fetch(); if($r)$r['tags']=item_tags($id); return $r?:null; }
function delete_item(int $id): void { $old=get_item($id); db()->prepare('DELETE FROM items WHERE id=?')->execute([$id]); audit_log('item',$id,'delete',$old,null); }
